services:
  - type: web
    name: mark-community
    runtime: python
    plan: free
    rootDir: 마크 커뮤니티
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RENDER
        value: "true"
      - key: RENDER_URL
        value: "https://minecraft-community-korea.onrender.com"
